# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mytime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('timeb', models.CharField(max_length=30)),
                ('timee', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
